version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          post-steps: # steps to run after steps defined in the job bar
              - elixir/use_build_cache:
                  env: test
                  regenerate: true
                  before-save:
                    - run: mix compile --force --warnings-as-errors
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          requires: 
            - elixir/build_test
          filters:
            <<: *filters
      - elixir/lint:
          filters:
            <<: *filters
          docs: false
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
