version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          pre-steps: # steps to run before steps defined in the job bar
            - checkout
            - elixir/get_mix_deps
            - run:
                command: mix compile --force
          filters:
            <<: *filters
      - elixir/lint:
          filters:
            <<: *filters
          docs: false
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
